// all film 请求
export const ALL_FILM_REQUEST = 'ALL_FILM_REQUEST';
export const ALL_FILM_SUCCESS = 'ALL_FILM_SUCCESS';
export const ALL_FILM_FAILURE = 'ALL_FILM_FAILURE';
export const ALL_FILM_CLEAN = 'ALL_FILM_CLEAN';

// 人气 film 请求
export const POPULARITY_FILM_REQUEST = 'POPULARITY_FILM_REQUEST';
export const POPULARITY_FILM_SUCCESS = 'POPULARITY_FILM_SUCCESS';
export const POPULARITY_FILM_FAILURE = 'POPULARITY_FILM_FAILURE';
export const POPULARITY_FILM_CLEAN = 'POPULARITY_FILM_CLEAN';

